name: Publish Module

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Generate module.json
      run: |
        echo '{
          "name": "fix-item-description-bug",
          "title": "Fix Item Description Bug",
          "description": "This module fixes the issue where identified descriptions are shown for unidentified items.",
          "version": "1.0.0",
          "author": "Your Name",
          "esmodules": ["scripts/fix-item-description.js"]
        }' > module.json

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "Changes detected"

    - name: Commit and Push changes
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git add module.json
        git commit -m "Update module.json"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

